#!/usr/bin/env python3
"""Canonical work-card field names for dream runtime code."""

FIELD_STATUS_REALM = "主角当前境界"
FIELD_STATUS_LOCATION = "主角当前位置"
FIELD_STATUS_INJURY = "主角当前伤势/疲劳"
FIELD_STATUS_EMOTION = "主角当前情绪"
FIELD_STATUS_GOAL = "主角当前目标"
FIELD_STATUS_CHANGE = "本章结束后的状态变化"
FIELD_STATUS_ELAPSED = "本章时间流逝"
FIELD_STATUS_TIMEPOINT = "本章结束时时间点"

STATUS_FIELDS = [
    FIELD_STATUS_LOCATION,
    FIELD_STATUS_INJURY,
    FIELD_STATUS_EMOTION,
    FIELD_STATUS_GOAL,
    FIELD_STATUS_CHANGE,
    FIELD_STATUS_ELAPSED,
    FIELD_STATUS_TIMEPOINT,
]

POWER_STATUS_FIELDS = [FIELD_STATUS_REALM, *STATUS_FIELDS]

FIELD_POWER_TARGET = "本章主要交手对象"
FIELD_POWER_LEVEL = "对方层级"
FIELD_POWER_CROSS = "主角是否越级"
FIELD_POWER_REASONABLE = "越级是否合理"
FIELD_POWER_NEW_TRUMP = "是否暴露新底牌"
FIELD_POWER_LOSS_RATIO = "具体战力损耗比例"
FIELD_POWER_TRUMP_NAME = "使用的底牌名称"
FIELD_POWER_AFTER_EFFECT = "本章战斗结果的后续影响"

POWER_CARD_FIELDS = [
    FIELD_POWER_TARGET,
    FIELD_POWER_LEVEL,
    FIELD_POWER_CROSS,
    FIELD_POWER_REASONABLE,
    FIELD_POWER_NEW_TRUMP,
    FIELD_POWER_LOSS_RATIO,
    FIELD_POWER_TRUMP_NAME,
    FIELD_POWER_AFTER_EFFECT,
]

FIELD_PLOT_CONFLICT = "核心冲突"
FIELD_PLOT_EVENT = "关键事件"
FIELD_PLOT_TURN = "转折点"
FIELD_PLOT_SETUP = "新埋伏笔"
FIELD_PLOT_PAYOFF = "回收伏笔"

PLOT_FIELDS = [
    FIELD_PLOT_CONFLICT,
    FIELD_PLOT_EVENT,
    FIELD_PLOT_TURN,
    FIELD_PLOT_SETUP,
    FIELD_PLOT_PAYOFF,
]

FIELD_RESOURCE_GAIN = "获得"
FIELD_RESOURCE_SPEND = "消耗"
FIELD_RESOURCE_LOSS = "损失"
FIELD_RESOURCE_CARRY = "需带到下章的状态"
FIELD_RESOURCE_SETUP = "伏笔"

RESOURCE_FIELDS = [
    FIELD_RESOURCE_GAIN,
    FIELD_RESOURCE_SPEND,
    FIELD_RESOURCE_LOSS,
    FIELD_RESOURCE_CARRY,
    FIELD_RESOURCE_SETUP,
]

FIELD_RELATION_MAIN = "主要人物"
FIELD_RELATION_CHANGE = "人物变化"

RELATION_FIELDS = [FIELD_RELATION_MAIN, FIELD_RELATION_CHANGE]

FIELD_EMOTION_START = "起始情绪"
FIELD_EMOTION_PROCESS = "变化过程"
FIELD_EMOTION_TARGET = "目标情绪"
FIELD_EMOTION_SUSPENSE = "悬念强度"

EMOTION_FIELDS = [
    FIELD_EMOTION_START,
    FIELD_EMOTION_PROCESS,
    FIELD_EMOTION_TARGET,
    FIELD_EMOTION_SUSPENSE,
]

FIELD_CARRY_MUST = "下章必须接住什么"
FIELD_CARRY_LIMIT = "下章不能忘什么限制"
FIELD_CARRY_PAYOFF = "需要回收的伏笔"
FIELD_CARRY_SETUP = "新埋下的伏笔"
FIELD_CARRY_HOOK = "本章留下的最强钩子是什么"

CARRY_FIELDS = [
    FIELD_CARRY_MUST,
    FIELD_CARRY_LIMIT,
    FIELD_CARRY_PAYOFF,
    FIELD_CARRY_SETUP,
    FIELD_CARRY_HOOK,
]
